apiVersion: v2
name: opnsense-ingress-operator
description: Kubernetes operator that syncs Ingress hostnames to OPNsense Unbound DNS host overrides
type: application
version: 0.1.3
appVersion: "v0.1.2"
keywords:
  - opnsense
  - unbound
  - dns
  - ingress
  - operator
  - networking
sources:
  - https://github.com/singularcurio/opnsense-ingress-operator
maintainers:
  - name: singularcurio
    url: https://github.com/singularcurio
